# cho postgres
version: "3.7"
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: xh_db
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "2022:5432"
