#  cho mysql
version: "3.1"

services:
    xh_db:
        image: mysql:5.7
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        command: --init-file /docker-entrypoint-initdb.d/init.sql
        ports:
            - "3312:3306"
        environment:
            MYSQL_DATABASE: xh_db
            MYSQL_ROOT_USER: uxh
            MYSQL_USER: uxh
            MYSQL_ROOT_PASSWORD: hellocacbantre
            MYSQL_PASSWORD: hellocacbantre
